"""AI-content disclosure: caption labelling and native platform flags.

The rule this encodes: from 2 August 2026 the EU AI Act Article 50 transparency
duties apply, and each platform has its own AI-labelling requirement. The label
must therefore survive every publish path and every caption limit.
"""
import asyncio
import dataclasses

import pytest

from aismm import config as config_module
from aismm import disclosure
from aismm.config import DisclosureSettings
from aismm.models import Account, Instruction, PlatformName, PublishMode, Run
from aismm.tools.publish_tool import perform_publish


@pytest.fixture(autouse=True)
def _on(monkeypatch):
    """Disclosure defaults to ON; conftest doesn't pin it, so pin it here."""
    monkeypatch.setattr(disclosure, "settings",
                        dataclasses.replace(config_module.settings,
                                            disclosure=DisclosureSettings()))


def _off(monkeypatch):
    monkeypatch.setattr(disclosure, "settings",
                        dataclasses.replace(config_module.settings,
                                            disclosure=DisclosureSettings(enabled=False)))


# --- caption labelling ------------------------------------------------------------ #

def test_label_is_appended():
    out = disclosure.apply_to_caption("A post about the news")
    assert out.startswith("A post about the news")
    assert out.endswith("🤖 AI-generated")


def test_disabled_leaves_the_caption_alone(monkeypatch):
    _off(monkeypatch)
    assert disclosure.apply_to_caption("Untouched") == "Untouched"


@pytest.mark.parametrize("caption", [
    "Made with AI, obviously",
    "This clip is ai-generated",
    "Generated by AI from public data",
    "A synthetic media experiment",
    "Fun times #ai #reels",
    "created with AI tools",
])
def test_existing_disclosure_is_not_duplicated(caption):
    assert disclosure.apply_to_caption(caption) == caption


def test_a_caption_without_disclosure_is_still_labelled():
    assert "AI-generated" in disclosure.apply_to_caption("Rainfall hit a record today")


def test_custom_label_text(monkeypatch):
    monkeypatch.setattr(disclosure, "settings",
                        dataclasses.replace(
                            config_module.settings,
                            disclosure=DisclosureSettings(text="Contenuto generato dall'IA",
                                                          separator=" — ")))
    assert disclosure.apply_to_caption("Notizie") == "Notizie — Contenuto generato dall'IA"


# --- caption limits (the label must never be the thing that gets cut) -------------- #

def test_caption_is_trimmed_to_make_room_for_the_label():
    caption = "x" * 300
    out = disclosure.apply_to_caption(caption, caption_limit=280)
    assert len(out) <= 280
    assert out.endswith("🤖 AI-generated")


def test_short_caption_within_limit_is_untouched_except_the_label():
    out = disclosure.apply_to_caption("Hello", caption_limit=280)
    assert out.startswith("Hello") and out.endswith("🤖 AI-generated")


def test_absurdly_small_limit_keeps_the_label_not_the_caption():
    out = disclosure.apply_to_caption("some text", caption_limit=10)
    assert len(out) <= 10
    assert "AI" in out


# --- native platform flags --------------------------------------------------------- #

def test_tiktok_uses_is_aigc():
    """TikTok's field is `is_aigc`; `is_ai_generated` is silently ignored."""
    assert disclosure.native_flags("tiktok") == {"is_aigc": True}


def test_youtube_uses_contains_synthetic_media():
    assert disclosure.native_flags("youtube") == {"containsSyntheticMedia": True}


@pytest.mark.parametrize("platform", ["instagram", "twitter"])
def test_platforms_without_an_api_field_get_no_flags(platform):
    """Meta and X have no per-post field today — the caption line is the disclosure."""
    assert disclosure.native_flags(platform) == {}


def test_no_flags_when_disabled(monkeypatch):
    _off(monkeypatch)
    assert disclosure.native_flags("tiktok") == {}


def test_tiktok_request_body_carries_the_flag():
    from aismm.platforms.tiktok import TikTok

    body_flags = disclosure.native_flags("tiktok")
    assert TikTok.capabilities.supports_video and body_flags["is_aigc"] is True


# --- enforcement through the publish gate ------------------------------------------ #

def _publish(store, mode, caption, platform=PlatformName.twitter):
    account = Account(platform=platform, handle="tester", external_id="1")
    store.upsert_account(account, access_token="t")
    instruction = store.upsert_instruction(Instruction(name="i", publish_mode=mode))
    run = store.add_run(Run(instruction_id=instruction.id, account_id=account.id))
    state = {"account": account, "instruction": instruction, "store": store, "run": run,
             "assets": []}
    asyncio.run(perform_publish(state, caption))
    return store.list_staged()[0]


def test_dry_run_preview_shows_the_disclosure(store):
    """The preview must show exactly what would be posted."""
    staged = _publish(store, PublishMode.dry_run, "Breaking: something happened")
    assert staged.caption.endswith("🤖 AI-generated")


def test_approval_queue_carries_the_disclosure(store):
    staged = _publish(store, PublishMode.approval, "Breaking: something happened")
    assert "AI-generated" in staged.caption


def test_disclosure_respects_the_platform_caption_limit(store):
    """The label always survives; the CAPTION is what gets trimmed.

    On X the budget is the whole thread (280 x 25), not one post — trimming to
    280 here would cut the caption before X could split it. Either way the label
    is never the thing that gets dropped.
    """
    from aismm.platforms.registry import get_platform

    caps = get_platform(PlatformName.twitter).capabilities
    budget = caps.caption_limit * caps.max_thread_posts

    staged = _publish(store, PublishMode.dry_run, "y" * 400)
    assert len(staged.caption) <= budget
    assert staged.caption.endswith("🤖 AI-generated")


def test_a_caption_past_even_the_thread_budget_still_keeps_the_label(store):
    from aismm.platforms.registry import get_platform

    caps = get_platform(PlatformName.twitter).capabilities
    budget = caps.caption_limit * caps.max_thread_posts

    staged = _publish(store, PublishMode.dry_run, "y" * (budget + 500))
    assert len(staged.caption) <= budget
    assert staged.caption.endswith("🤖 AI-generated")


# --- per-instruction opt-out (the dashboard checkbox) ------------------------------- #

def test_instruction_can_opt_out(store):
    """A checkbox on the instruction, so one account can post unlabelled."""
    off = Instruction(name="no label", publish_mode=PublishMode.dry_run, disclose_ai=False)
    assert disclosure.enabled(off) is False
    assert disclosure.apply_to_caption("A post", instruction=off) == "A post"
    assert disclosure.native_flags("tiktok", off) == {}


def test_instruction_opted_in_still_gets_the_label():
    on = Instruction(name="labelled", disclose_ai=True)
    assert disclosure.enabled(on) is True
    assert "AI-generated" in disclosure.apply_to_caption("A post", instruction=on)
    assert disclosure.native_flags("tiktok", on) == {"is_aigc": True}


def test_the_global_switch_still_wins(monkeypatch):
    """AI_DISCLOSURE_ENABLED=0 turns everything off, whatever an instruction says."""
    monkeypatch.setattr(disclosure, "settings",
                        dataclasses.replace(config_module.settings,
                                            disclosure=DisclosureSettings(enabled=False)))
    assert disclosure.enabled(Instruction(name="x", disclose_ai=True)) is False


def test_defaults_to_on_for_a_new_instruction():
    assert Instruction(name="new").disclose_ai is True


def test_publish_respects_the_instruction_flag(store):
    from aismm.models import Account, PlatformName, Run

    account = store.upsert_account(Account(platform=PlatformName.twitter, handle="t",
                                           external_id="1"), access_token="x")
    instruction = store.upsert_instruction(Instruction(
        name="quiet", publish_mode=PublishMode.dry_run, disclose_ai=False))
    run = store.add_run(Run(instruction_id=instruction.id, account_id=account.id))
    state = {"account": account, "instruction": instruction, "store": store, "run": run,
             "assets": []}
    asyncio.run(perform_publish(state, "A clean caption"))
    assert store.list_staged()[0].caption == "A clean caption"


def test_the_form_round_trips_the_checkbox(store, monkeypatch):
    from aismm.dashboard import app as app_module

    monkeypatch.setattr(app_module, "get_store", lambda: store)
    app = app_module.create_app()
    app.secret_key = "test"
    instruction = store.upsert_instruction(Instruction(name="i"))

    base = {"id": instruction.id, "name": "i", "brief": "b", "schedule": "",
            "publish_mode": "dry_run", "media_pref": "auto", "note": ""}
    app.test_client().post("/instructions", data=base)                     # unticked
    assert store.get_instruction(instruction.id).disclose_ai is False
    app.test_client().post("/instructions", data={**base, "disclose_ai": "on"})
    assert store.get_instruction(instruction.id).disclose_ai is True
