"""Azure Table + Blob store adapter — OPTIONAL, interface-complete STUB.

The SandBox projects keep all state in Azure Table Storage (rows keyed by a flat
date) + Blob Storage (media). AISMM ships with the local SQLite store by default,
but this module documents exactly how to reach parity with that ecosystem:

* Accounts / Instructions / Runs / StagedPosts -> one Azure Table each
  (``azure-data-tables``), PartitionKey = entity type, RowKey = id.
* Encrypted token blobs -> the ``*_enc`` fields, unchanged (Fernet still applies).
* Generated media -> Azure Blob (``azure-storage-blob``); this also gives
  Instagram the PUBLIC media URL it requires (enable anonymous blob read or a
  SAS URL) instead of serving via the dashboard.
* ``acquire_lock`` -> ``create_entity`` on a locks table; ``ResourceExistsError``
  means "held", with a TTL reclaim — identical to ``GenBox/azurestorage.py``'s
  ``_try_acquire_lock``.

To activate: implement the methods below against ``TableServiceClient`` /
``BlobServiceClient`` using ``connection_string`` from the environment, then
return ``AzureStore()`` from :func:`aismm.store.get_store`.
"""
from __future__ import annotations

from .base import Store


class AzureStore(Store):  # pragma: no cover - scaffold for future implementation
    def __init__(self) -> None:
        raise NotImplementedError(
            "AzureStore is a documented scaffold. Implement the Store methods "
            "against azure-data-tables / azure-storage-blob (see module docstring), "
            "add `connection_string` to your .env, and wire it into "
            "aismm.store.get_store()."
        )

    def init(self) -> None: ...
    def upsert_account(self, account, *, access_token=None, refresh_token=None): ...
    def get_account(self, account_id): ...
    def list_accounts(self): ...
    def delete_account(self, account_id): ...
    def get_tokens(self, account_id): ...
    def upsert_instruction(self, instruction): ...
    def get_instruction(self, instruction_id): ...
    def list_instructions(self, *, enabled_only=False): ...
    def delete_instruction(self, instruction_id): ...
    def add_run(self, run): ...
    def update_run(self, run): ...
    def list_runs(self, *, limit=100): ...
    def add_staged(self, staged): ...
    def get_staged(self, staged_id): ...
    def update_staged(self, staged): ...
    def list_staged(self, *, pending_only=False, limit=100): ...
    def acquire_lock(self, key, ttl_seconds=3600): ...
    def release_lock(self, key): ...
